---
hitheme     : tomorrow
author      : Michael W. Kearney
school      : School of Journalism<br>Informatics Institute
university  : University of Missouri
title       : goodslides: Kansas theme
---

## rtweet pkg

- Load packages

```{r, eval=FALSE}
## load rtweet dplyr and ggplot2
library(rtweet)
library(dplyr)
library(ggplot2)
```


- Stream tweets with R tweet package

```{r, eval=FALSE}
## stream
rt <- stream_tweets(timeout = 30, verbose = FALSE)
## group by english and non-english
rt$eng <- ifelse(
    rt$lang == "en" & !is.na(rt$lang), "English", "Non-English"
  )
rt <- group_by(rt, eng)
```

---

## Plot time series of tweets

- `ts_data` and `trimts` are useful rtweet functions

```{r, eval=FALSE}
ts_data(rt, "5 secs") %>%
  trimts(1, 1) %>%
  ggplot(aes(x = time, y = n)) +
  geom_smooth(method = "loess", aes(group = eng), colour = "#aa00cc", alpha = .3) +
  geom_point(aes(fill = eng), shape = 21, size = 3.5, alpha = .7) +
  labs(title = "Filtering Twitter's stream API using stop words",
       subtitle = "Tweets collected and aggregated in 10 second
	   intervals in R using rtweet") +
  ggthemes::theme_fivethirtyeight(base_size = 18) +
  theme(legend.title = element_blank()) +
  scale_color_manual(values = c("#5577fa", "#df6666")) +
  scale_fill_manual(values = c("#5577fa", "#df6666"))
```

- The plot looks nice, I promise.


---

## R code example

- Basic R code with output

```{r, eval=TRUE}
foo <- function(n) {
  data.frame(
    var1 = rnorm(n),
	var2 = rnorm(n)
  )
}
df <- foo(10)
print(df)
```


--- .transition

## And now some content

---

## Content

**Exposure to diversity higher than ever**
- Travel
- Technology
- Trade
- Television

--- .transition

## That's all!
